rework modbus polling
NubeIO/rubix-point-server pull request #139
Opened 2020-12-03 04:51 UTC by Shiny380

- [ ] Device Ping Endpoint (Resolves #133 )
- [x] Polling Rework (Resolves #114 )
    - utilises `network` and `device` fault values
    - skip polling of network if unreachable and device if unreachable ping_point
- [ ] Configurable poll loop time (Resolves #130 )

2020-12-07 05:24 UTC, RaiBnod requested changes

2020-12-07 05:24 UTC, RaiBnod commented on src/source_drivers/modbus/resources/point/point_singular.py
> +    def get(cls):
Make it post instead of `GET` and can you share the JSON `body` example.

2020-12-07 05:48 UTC, Shiny380 commented on src/event_dispatcher.py
> -                    break
yeh I had the problem of modbus TCP and RTU running different threads/services but no way of telling from higher up which one to pass the event to without adding a bunch of stuff so I based it of the `driver` column in the polymorphic tables and added the `HandledByDifferentService` exception so the TCP and RTU threads could determine themselves if it was meant for them or not

2020-12-08 02:49 UTC, merged

2020-12-08 02:51 UTC, RaiBnod commented on src/source_drivers/modbus/resources/point/point_singular.py
> +    def get(cls):
Adding an example:

`POST`: `http://{{bac_rest_ip}}:{{bac_rest_port}}/api/modbus/poll/point`
```{
      "network_type": "RTU",
      "network_rtu_port": "/dev/ttyUSB0", 
      "device_address": 1,
      "point_register": 1,
      "point_register_length": 2,
      "point_function_code": "READ_INPUT_REGISTERS",
      "point_data_type": "FLOAT",
      "point_write_value": 0
  }```