Implement Generic Point
NubeIO/rubix-point-server pull request #152
Opened 2020-12-11 06:19 UTC by Shiny380

### Summary
- implemented generic point that listened to updates over MQTT
- MQTT client separated into base class for common tasks
### Other
- `loggin.conf` changed to `logging.example.conf like settings to avoid accidental changes
- `system` endpoint return details changed
- model `find_by_name` args and endpoints changed due to name unique constraint changes
- `PointStoreModel` update method and value modifications moved to `PointModel` for better separation of concerns
### TODO
- [ ] model `updated/created_on` column fix
- [ ] move history
- [ ] move common flask rest resources

2020-12-14 22:40 UTC, Shiny380 commented
@RaiBnod take note of the [src/system/resources/ping.py](https://github.com/NubeIO/rubix-point-server/compare/master...feature/generic-point#diff-63197df2a43a41a201e9b8218d4db4437c035e4550934d8fc6740cd0684f5d68) changes for any front-end related calls. would be good any front end stuff isn't attribute dependant so changes can be made without breaking the front end

2020-12-15 16:08 UTC, RaiBnod requested changes

2020-12-15 16:08 UTC, RaiBnod commented on src/source_drivers/generic/services/generic_point_listener.py
> +GENERIC_POINT_MQTT_TOPIC_EXAMPLE = f'{GENERIC_POINT_MQTT_TOPIC}/point_name/device_name/network_name'
`GENERIC_POINT_MQTT_TOPIC_EXAMPLE = f'{GENERIC_POINT_MQTT_TOPIC}/<point_name>/<device_name>/<network_name>'`

This would be more meaningful.

2020-12-15 16:08 UTC, RaiBnod commented on src/models/point/model_point.py
> +            raise Exception(f'Cannot find network or device for point {self.point_uuid}')
`raise Exception(f'Cannot find network or device for point {self.uuid}')`

There is no `point_uuid` on this model.

2020-12-15 20:00 UTC, merged