Add postgresql history sync
NubeIO/rubix-point-server pull request #227
Opened 2021-02-15 16:48 UTC by enjuthulung

Resolves: CU-25ch1w

### Summary

- Added PostgreSQL history sync

2021-02-15 21:08 UTC, NubeDev commented
Can you please make it that user can enter remote from the `config.json` database details not just localhost

https://github.com/NubeIO/rubix-point-server/pull/227/files#diff-432b65341693b39cec1910af65ba4d2613b52dde3322838fa6ee20cc72fe0ffcR55

2021-02-16 03:01 UTC, RaiBnod requested changes

2021-02-16 03:01 UTC, RaiBnod commented on tests/setting_dump.py
> +        "history_sync": true,
Change it into `history_sync_influxdb`

2021-02-16 03:01 UTC, RaiBnod commented on tests/setting_dump.py
> +        "history_sync_postgres": true
Add your config example for postgres.

2021-02-17 04:49 UTC, RaiBnod requested changes

2021-02-17 04:49 UTC, RaiBnod commented on src/services/histories/sync/postgresql.py
> +            logger.info(f'Stored {len(store)} rows on {self.config.table_name} table')
These are done for bulk insertion on InfluxDB, it should show exceptions but exceptions are handled so app is not crashing.

2021-02-17 04:49 UTC, RaiBnod commented on src/services/histories/sync/postgresql.py
> +                            curs.execute(query, data)
Can you see on bulk insertion as like this:

```sql
INSERT INTO films (code, title, did, date_prod, kind) VALUES
    ('B6717', 'Tampopo', 110, '1985-02-10', 'Comedy'),
    ('HG120', 'The Dinner Game', 140, DEFAULT, 'Comedy');
```

2021-02-17 04:49 UTC, RaiBnod commented on src/services/histories/sync/postgresql.py
> +                f' {self.config.table_name}_details(point_uuid));'
Space on end instead of on starting would have been good formatting.

2021-02-18 04:49 UTC, RaiBnod requested changes
Also there is two `device_name` one from `wires_plat` & another from `history point`. Make `edge_device_uuid` & `edge_device_name` for `history_point` and leave `device_name` & `device_id`. Make sure this changes should be for both `InfluxDB` tags and `history_details`.

2021-02-18 04:49 UTC, RaiBnod commented on src/services/histories/sync/postgresql.py
> +            logger.debug(f"Storing: {store}")
No, needs of have that row and store. Just use:
```python
        if len(data_history):
            logger.info(f"Storing data_detail: {data_detail}")
            logger.info(f"Storing data_history: {data_history}")
```

2021-02-18 04:52 UTC, RaiBnod commented on config/config.example.json
> +        "attempt_reconnect_secs": 5
Make same format as others.

2021-02-18 17:18 UTC, RaiBnod approved these changes

2021-02-18 17:19 UTC, merged